/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.correo;

/**
 *
 * @author piero
 */
public class Interfaz_Registro extends javax.swing.JFrame {

  /**
   * Creates new form Interfaz_Registro
   */
  public Interfaz_Registro() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    BGRegister = new javax.swing.JPanel();
    HeaderRegister = new javax.swing.JPanel();
    IconEfelante = new javax.swing.JLabel();
    InfoInterfaz = new javax.swing.JLabel();
    InterfazRegister = new javax.swing.JPanel();
    txt1 = new javax.swing.JLabel();
    SeparadorTxt1 = new javax.swing.JSeparator();
    txt2 = new javax.swing.JLabel();
    txt3 = new javax.swing.JLabel();
    image1 = new javax.swing.JLabel();
    image2 = new javax.swing.JLabel();
    image3 = new javax.swing.JLabel();
    BtnRegresar = new javax.swing.JPanel();
    txtRegresar = new javax.swing.JLabel();
    BackgroundColorRegister = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);

    BGRegister.setBackground(new java.awt.Color(255, 255, 255));
    BGRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    IconEfelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Logo (1).png"))); // NOI18N

    InfoInterfaz.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
    InfoInterfaz.setForeground(new java.awt.Color(204, 204, 204));
    InfoInterfaz.setText("Interfaz - Registro");

    javax.swing.GroupLayout HeaderRegisterLayout = new javax.swing.GroupLayout(HeaderRegister);
    HeaderRegister.setLayout(HeaderRegisterLayout);
    HeaderRegisterLayout.setHorizontalGroup(
      HeaderRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(HeaderRegisterLayout.createSequentialGroup()
        .addComponent(IconEfelante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(InfoInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 194, Short.MAX_VALUE))
    );
    HeaderRegisterLayout.setVerticalGroup(
      HeaderRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(IconEfelante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(InfoInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    BGRegister.add(HeaderRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

    InterfazRegister.setBackground(new java.awt.Color(255, 255, 255));
    InterfazRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txt1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    txt1.setForeground(new java.awt.Color(51, 51, 51));
    txt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txt1.setText("Ahora eres usuario de \"Correos DonGil\"!!!");
    InterfazRegister.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 310, 64));

    SeparadorTxt1.setBackground(new java.awt.Color(138, 117, 242));
    SeparadorTxt1.setForeground(new java.awt.Color(138, 117, 242));
    InterfazRegister.add(SeparadorTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 320, 10));

    txt2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    txt2.setForeground(new java.awt.Color(102, 102, 102));
    txt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txt2.setText("Gracias por contar con nosotros :D");
    InterfazRegister.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 300, 30));

    txt3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    txt3.setForeground(new java.awt.Color(102, 102, 102));
    txt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txt3.setText("Dale click al botón \"Regresar\" para empezar...");
    InterfazRegister.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 320, 30));

    image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Party.png"))); // NOI18N
    InterfazRegister.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

    image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Party.png"))); // NOI18N
    InterfazRegister.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

    image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Party.png"))); // NOI18N
    InterfazRegister.add(image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

    BtnRegresar.setBackground(new java.awt.Color(138, 117, 242));
    BtnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtnRegresarMouseClicked(evt);
      }
    });

    txtRegresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    txtRegresar.setForeground(new java.awt.Color(51, 51, 51));
    txtRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtRegresar.setText("Regresar");

    javax.swing.GroupLayout BtnRegresarLayout = new javax.swing.GroupLayout(BtnRegresar);
    BtnRegresar.setLayout(BtnRegresarLayout);
    BtnRegresarLayout.setHorizontalGroup(
      BtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
    );
    BtnRegresarLayout.setVerticalGroup(
      BtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
    );

    InterfazRegister.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, 30));

    BGRegister.add(InterfazRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 320, 290));

    BackgroundColorRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/178 Gagarin View.png"))); // NOI18N
    BGRegister.add(BackgroundColorRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 380, 340));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(BGRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(BGRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void BtnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseClicked
    LoginCorreo Login = new LoginCorreo();
    Login.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_BtnRegresarMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Interfaz_Registro().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel BGRegister;
  private javax.swing.JLabel BackgroundColorRegister;
  private javax.swing.JPanel BtnRegresar;
  private javax.swing.JPanel HeaderRegister;
  private javax.swing.JLabel IconEfelante;
  private javax.swing.JLabel InfoInterfaz;
  private javax.swing.JPanel InterfazRegister;
  private javax.swing.JSeparator SeparadorTxt1;
  private javax.swing.JLabel image1;
  private javax.swing.JLabel image2;
  private javax.swing.JLabel image3;
  private javax.swing.JLabel txt1;
  private javax.swing.JLabel txt2;
  private javax.swing.JLabel txt3;
  private javax.swing.JLabel txtRegresar;
  // End of variables declaration//GEN-END:variables
}
