/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.correo;

/**
 *
 * @author piero
 */
public class Interfaz_Registrar extends javax.swing.JFrame {

  /**
   * Creates new form Interfaz_Registrar
   */
  public Interfaz_Registrar() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    BGResgistro = new javax.swing.JPanel();
    HeaderRegistro = new javax.swing.JPanel();
    IconInterfaz = new javax.swing.JLabel();
    NameInterfaz = new javax.swing.JLabel();
    InterfazRegistro = new javax.swing.JPanel();
    InfoRegistro = new javax.swing.JLabel();
    InfoCorreo = new javax.swing.JLabel();
    txtCorreo = new javax.swing.JTextField();
    SeparadorCorreo = new javax.swing.JSeparator();
    InfoContra = new javax.swing.JLabel();
    txtContra = new javax.swing.JTextField();
    SeparadorContra = new javax.swing.JSeparator();
    InfoConfirmación = new javax.swing.JLabel();
    txtConfirmacion = new javax.swing.JTextField();
    SeparadorConfirmacion = new javax.swing.JSeparator();
    BtnRegistrarse = new javax.swing.JPanel();
    txtRegistrarse = new javax.swing.JLabel();
    BackgroundColorRegistro = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);

    BGResgistro.setBackground(new java.awt.Color(255, 255, 255));
    BGResgistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    HeaderRegistro.setBackground(new java.awt.Color(0, 0, 0));

    IconInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Logo (1).png"))); // NOI18N

    NameInterfaz.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
    NameInterfaz.setForeground(new java.awt.Color(204, 204, 204));
    NameInterfaz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    NameInterfaz.setText("Interfaz - Registrar");
    NameInterfaz.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

    javax.swing.GroupLayout HeaderRegistroLayout = new javax.swing.GroupLayout(HeaderRegistro);
    HeaderRegistro.setLayout(HeaderRegistroLayout);
    HeaderRegistroLayout.setHorizontalGroup(
      HeaderRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(HeaderRegistroLayout.createSequentialGroup()
        .addComponent(IconInterfaz)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(NameInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 245, Short.MAX_VALUE))
    );
    HeaderRegistroLayout.setVerticalGroup(
      HeaderRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(NameInterfaz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(IconInterfaz, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    BGResgistro.add(HeaderRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

    InterfazRegistro.setBackground(new java.awt.Color(255, 255, 255));

    InfoRegistro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    InfoRegistro.setForeground(new java.awt.Color(102, 102, 102));
    InfoRegistro.setText("Registro de nuevo correo");

    InfoCorreo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    InfoCorreo.setForeground(new java.awt.Color(138, 117, 242));
    InfoCorreo.setText("Correo");

    txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
    txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
    txtCorreo.setText("Ingrese su correo");
    txtCorreo.setBorder(null);

    SeparadorCorreo.setBackground(new java.awt.Color(138, 117, 242));
    SeparadorCorreo.setForeground(new java.awt.Color(138, 117, 242));

    InfoContra.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    InfoContra.setForeground(new java.awt.Color(138, 117, 242));
    InfoContra.setText("Contraseña");

    txtContra.setBackground(new java.awt.Color(255, 255, 255));
    txtContra.setForeground(new java.awt.Color(204, 204, 204));
    txtContra.setText("Ingrese una contraseña");
    txtContra.setBorder(null);

    SeparadorContra.setBackground(new java.awt.Color(138, 117, 242));
    SeparadorContra.setForeground(new java.awt.Color(138, 117, 242));

    InfoConfirmación.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
    InfoConfirmación.setForeground(new java.awt.Color(138, 117, 242));
    InfoConfirmación.setText("Confirmación");

    txtConfirmacion.setBackground(new java.awt.Color(255, 255, 255));
    txtConfirmacion.setForeground(new java.awt.Color(204, 204, 204));
    txtConfirmacion.setText("Confirme su contraseña");
    txtConfirmacion.setBorder(null);

    SeparadorConfirmacion.setBackground(new java.awt.Color(138, 117, 242));
    SeparadorConfirmacion.setForeground(new java.awt.Color(138, 117, 242));

    BtnRegistrarse.setBackground(new java.awt.Color(215, 187, 247));
    BtnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    BtnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtnRegistrarseMouseClicked(evt);
      }
    });

    txtRegistrarse.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    txtRegistrarse.setForeground(new java.awt.Color(51, 51, 51));
    txtRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtRegistrarse.setText("Registrarse");

    javax.swing.GroupLayout BtnRegistrarseLayout = new javax.swing.GroupLayout(BtnRegistrarse);
    BtnRegistrarse.setLayout(BtnRegistrarseLayout);
    BtnRegistrarseLayout.setHorizontalGroup(
      BtnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
    );
    BtnRegistrarseLayout.setVerticalGroup(
      BtnRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout InterfazRegistroLayout = new javax.swing.GroupLayout(InterfazRegistro);
    InterfazRegistro.setLayout(InterfazRegistroLayout);
    InterfazRegistroLayout.setHorizontalGroup(
      InterfazRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InterfazRegistroLayout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(InterfazRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(SeparadorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(InterfazRegistroLayout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addGroup(InterfazRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(BtnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(InterfazRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(InfoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(InfoContra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SeparadorContra, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(SeparadorConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(InfoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(InfoConfirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addContainerGap(51, Short.MAX_VALUE))
    );
    InterfazRegistroLayout.setVerticalGroup(
      InterfazRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InterfazRegistroLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(InfoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(InfoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(4, 4, 4)
        .addComponent(SeparadorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(InfoContra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(SeparadorContra, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(InfoConfirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(txtConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(SeparadorConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(32, 32, 32)
        .addComponent(BtnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );

    BGResgistro.add(InterfazRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 340, 410));

    BackgroundColorRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    BackgroundColorRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/178 Gagarin View.png"))); // NOI18N
    BGResgistro.add(BackgroundColorRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 470));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(BGResgistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(BGResgistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void BtnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarseMouseClicked
    Interfaz_Registro Registro = new Interfaz_Registro();
    Registro.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_BtnRegistrarseMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Interfaz_Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Interfaz_Registrar().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel BGResgistro;
  private javax.swing.JLabel BackgroundColorRegistro;
  private javax.swing.JPanel BtnRegistrarse;
  private javax.swing.JPanel HeaderRegistro;
  private javax.swing.JLabel IconInterfaz;
  private javax.swing.JLabel InfoConfirmación;
  private javax.swing.JLabel InfoContra;
  private javax.swing.JLabel InfoCorreo;
  private javax.swing.JLabel InfoRegistro;
  private javax.swing.JPanel InterfazRegistro;
  private javax.swing.JLabel NameInterfaz;
  private javax.swing.JSeparator SeparadorConfirmacion;
  private javax.swing.JSeparator SeparadorContra;
  private javax.swing.JSeparator SeparadorCorreo;
  private javax.swing.JTextField txtConfirmacion;
  private javax.swing.JTextField txtContra;
  private javax.swing.JTextField txtCorreo;
  private javax.swing.JLabel txtRegistrarse;
  // End of variables declaration//GEN-END:variables
}
