package com.correo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author piero
 */
public class SalidaCorreo extends javax.swing.JFrame {

  /**
   * Creates new form SalidaCorreo
   */
  public SalidaCorreo() {
    initComponents();
    this.setLocationRelativeTo(null);
    
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    BackgroundGeneral = new javax.swing.JPanel();
    HeaderSalida = new javax.swing.JPanel();
    IconInterfaz = new javax.swing.JLabel();
    NameInterfaz = new javax.swing.JLabel();
    txtSalida = new javax.swing.JLabel();
    BtnNO = new javax.swing.JPanel();
    txtNo = new javax.swing.JLabel();
    BtnYES = new javax.swing.JPanel();
    txtYES = new javax.swing.JLabel();
    BackgroundSalida = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);
    setResizable(false);

    BackgroundGeneral.setBackground(new java.awt.Color(204, 255, 255));
    BackgroundGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    HeaderSalida.setBackground(new java.awt.Color(0, 0, 0));

    IconInterfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/Logo (1).png"))); // NOI18N

    NameInterfaz.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
    NameInterfaz.setForeground(new java.awt.Color(204, 204, 204));
    NameInterfaz.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    NameInterfaz.setText("Interfaz - Salida");
    NameInterfaz.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

    javax.swing.GroupLayout HeaderSalidaLayout = new javax.swing.GroupLayout(HeaderSalida);
    HeaderSalida.setLayout(HeaderSalidaLayout);
    HeaderSalidaLayout.setHorizontalGroup(
      HeaderSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(HeaderSalidaLayout.createSequentialGroup()
        .addComponent(IconInterfaz)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(NameInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 145, Short.MAX_VALUE))
    );
    HeaderSalidaLayout.setVerticalGroup(
      HeaderSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(NameInterfaz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(IconInterfaz, javax.swing.GroupLayout.Alignment.TRAILING)
    );

    BackgroundGeneral.add(HeaderSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 30));

    txtSalida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    txtSalida.setForeground(new java.awt.Color(51, 51, 51));
    txtSalida.setText("¿Seguro que quieres salir?");
    BackgroundGeneral.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

    BtnNO.setBackground(new java.awt.Color(215, 187, 247));
    BtnNO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    BtnNO.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtnNOMouseClicked(evt);
      }
    });

    txtNo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    txtNo.setForeground(new java.awt.Color(51, 51, 51));
    txtNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtNo.setText("No");

    javax.swing.GroupLayout BtnNOLayout = new javax.swing.GroupLayout(BtnNO);
    BtnNO.setLayout(BtnNOLayout);
    BtnNOLayout.setHorizontalGroup(
      BtnNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
    );
    BtnNOLayout.setVerticalGroup(
      BtnNOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
    );

    BackgroundGeneral.add(BtnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 90, 30));

    BtnYES.setBackground(new java.awt.Color(215, 187, 247));
    BtnYES.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    BtnYES.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        BtnYESMouseClicked(evt);
      }
    });

    txtYES.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    txtYES.setForeground(new java.awt.Color(51, 51, 51));
    txtYES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    txtYES.setText("Si");

    javax.swing.GroupLayout BtnYESLayout = new javax.swing.GroupLayout(BtnYES);
    BtnYES.setLayout(BtnYESLayout);
    BtnYESLayout.setHorizontalGroup(
      BtnYESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtYES, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
    );
    BtnYESLayout.setVerticalGroup(
      BtnYESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(txtYES, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
    );

    BackgroundGeneral.add(BtnYES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 30));

    BackgroundSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images2/178 Gagarin View.png"))); // NOI18N
    BackgroundGeneral.add(BackgroundSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 180));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(BackgroundGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(BackgroundGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void BtnYESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnYESMouseClicked
    LoginCorreo Login = new LoginCorreo();
    Login.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_BtnYESMouseClicked

  private void BtnNOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNOMouseClicked
    Interfaz_Correo Correo = new Interfaz_Correo();
    Correo.setVisible(true);
    this.setVisible(false);
  }//GEN-LAST:event_BtnNOMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(SalidaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(SalidaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(SalidaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(SalidaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new SalidaCorreo().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel BackgroundGeneral;
  private javax.swing.JLabel BackgroundSalida;
  private javax.swing.JPanel BtnNO;
  private javax.swing.JPanel BtnYES;
  private javax.swing.JPanel HeaderSalida;
  private javax.swing.JLabel IconInterfaz;
  private javax.swing.JLabel NameInterfaz;
  private javax.swing.JLabel txtNo;
  private javax.swing.JLabel txtSalida;
  private javax.swing.JLabel txtYES;
  // End of variables declaration//GEN-END:variables
}
